/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/kast6.gltf
*/
import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useConfigurator } from "../contexts/Configurator";
import { useFrame } from "@react-three/fiber";

export default function Kast6(props) {
  const { nodes, materials } = useGLTF("/models/kast7.gltf");

  const { closetWidth } = useConfigurator();

  const top = useRef();
  const bottom = useRef();
  const back = useRef();

  const right = useRef();

  useFrame((_state, delta) => {
    const closetWidthScale = closetWidth / 60;
    const targetScale = new THREE.Vector3(
      1,
      1,
      (60 * closetWidthScale + 4 * (closetWidthScale - 1)) / 60
    );

    const backScale = new THREE.Vector3(1, 1, 1 * closetWidthScale);

    top.current.scale.lerp(targetScale, delta * 12);
    bottom.current.scale.lerp(targetScale, delta * 12);

    back.current.scale.lerp(backScale, delta * 12);

    const targetRightSide = new THREE.Vector3(
      0,
      0,
      -0.6 * closetWidthScale + 0.02
    );

    // - (60 * closetWidthScale + (1.8 * -(closetWidthScale - 1)) / 60)
    right.current.position.lerp(targetRightSide, delta * 12);
  });

  return (
    <group {...props} dispose={null} rotation={[0, Math.PI * 0.5, 0]}>
      <mesh geometry={nodes.links.geometry} material={materials.blauw} />
      <mesh
        geometry={nodes.rechts.geometry}
        material={materials.blauw}
        ref={right}
      />
      <mesh
        geometry={nodes.onder.geometry}
        material={materials.groen}
        position={[0, 0, -0.02]}
        ref={bottom}
      />
      <mesh
        geometry={nodes.boven.geometry}
        material={materials.groen}
        position={[0, 0.58, -0.02]}
        ref={top}
      />
      <mesh
        geometry={nodes.achter.geometry}
        material={materials.rood}
        position={[-0.59, 0, 0]}
        ref={back}
      />
    </group>
  );
}

useGLTF.preload("/models/kast7.gltf");
