/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/lowPolyRoom.gltf
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Room(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/lowPolyRoom.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          position={[-3.84, 1.02, 0.74]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.4}
        >
          <primitive object={nodes.base} />
          <skinnedMesh
            name="MAN"
            geometry={nodes.MAN.geometry}
            material={materials["Material.002"]}
            skeleton={nodes.MAN.skeleton}
          />
        </group>
        <group name="room" position={[2.58, 0.12, 10.35]}>
          <mesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={materials.chair}
          />
          <mesh
            name="Cube005_1"
            geometry={nodes.Cube005_1.geometry}
            material={materials.room}
          />
          <mesh
            name="Cube005_2"
            geometry={nodes.Cube005_2.geometry}
            material={materials.table}
          />
          <mesh
            name="Cube005_3"
            geometry={nodes.Cube005_3.geometry}
            material={materials.bed}
          />
          <mesh
            name="Cube005_4"
            geometry={nodes.Cube005_4.geometry}
            material={materials.cushion}
          />
          <mesh
            name="Cube005_5"
            geometry={nodes.Cube005_5.geometry}
            material={materials.borders}
          />
          <mesh
            name="Cube005_6"
            geometry={nodes.Cube005_6.geometry}
            material={materials.book}
          />
          <mesh
            name="Cube005_7"
            geometry={nodes.Cube005_7.geometry}
            material={materials["painting 1"]}
          />
          <mesh
            name="Cube005_8"
            geometry={nodes.Cube005_8.geometry}
            material={materials["painting 2"]}
          />
        </group>
        <group
          name="BOOK'"
          position={[-4.94, 1.39, 0.7]}
          scale={[0.6, 0.06, 1]}
        >
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Cube_1"
            geometry={nodes.Cube_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Circle016"
          position={[1.56, 5.1, -2.65]}
          rotation={[Math.PI / 2, -1.52, Math.PI / 2]}
          scale={2.46}
        >
          <mesh
            name="Circle006"
            geometry={nodes.Circle006.geometry}
            material={materials.Uhr_2}
          />
          <mesh
            name="Circle006_1"
            geometry={nodes.Circle006_1.geometry}
            material={materials["Material.005"]}
          />
          <group
            name="Empty001"
            position={[0.07, 0, 0]}
            rotation={[-0.05, 0, 0]}
          >
            <mesh
              name="Cube002"
              geometry={nodes.Cube002.geometry}
              material={materials.min_Zeiger}
              position={[-0.02, 0, 0]}
              rotation={[1.61, 0, 0]}
            />
          </group>
          <group
            name="Empty002"
            position={[0.1, 0, 0]}
            rotation={[0.4, 0.06, -0.16]}
          >
            <mesh
              name="Cube003"
              geometry={nodes.Cube003.geometry}
              material={materials.min_Zeiger}
              position={[-0.05, 0, 0]}
              rotation={[0.2, 0, 0]}
            />
          </group>
          <group name="Empty" position={[0.05, 0, 0]} rotation={[-0.05, 0, 0]}>
            <mesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials.Sec_Zeiger}
              rotation={[0.79, 0, 0]}
            />
          </group>
        </group>
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.001"]}
          position={[-6.07, 3.37, 0.58]}
          scale={[0.5, 0.18, 0.5]}
        />
        <mesh
          name="room001"
          geometry={nodes.room001.geometry}
          material={materials.chair}
          position={[-3.2, 0.18, 0.73]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/lowPolyRoom.gltf");

export default Room;
